version: '3'

services:

  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - ./certs:/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - quiz

  quiz:
    build:
      context: .
    container_name: quiz
    volumes:
      - ./data:/home/user/data
    environment:
      - ACCESS=$ACCESS